spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  frontendBaseUrl: http://localhost:4200
